### ISSUE TITLE
requests.exceptions.SSLError: hostname

### ISSUE THREAD

**Issue by johnlabarge** [kelproject/pykube#125]
When I try to use the instructions from the documentation to  connect to a GKE cluster using the config file it fails with the dreaded: "requests.exceptions.SSLError: hostname."   I expect this to work by not validating the hostname and instead validating the cert. 

The workaround is to use kubectl proxy and http://localhost:8001 which is just an extra step for the user. It would be nice if requests could turn host validation off in this case, but there is no such feature in that library.  I filed a [feature request](https://github.com/kennethreitz/requests/issues/3955#issuecomment-291876110) with it as well, but it is basically rejected. 

It may be worth updating the docs to deal with this.

**Comment by brosner** [comment]
I am hoping this is fixed with the change in 2f06f601e32825bd1b7e925e3989f2a920090425. If it is not then I am happy to add in more docs.
