### ISSUE TITLE
support for no-auth kube-apiserver access

### ISSUE THREAD

**Issue by davidsiefert** [kelproject/pykube#18]
I am accessing a kubernetes cluster with no auth required for convenience.  The http client currently errors out when it cannot find the right credentials, when none are actually needed.

**Comment by davidsiefert** [comment]
i can submit a PR, just wanted to confirm if it is worth supporting this?

**Comment by jtauber** [comment]
@davidsiefert sounds good to me. @brosner any objections?

**Comment by cdrage** [comment]
Funny enough i'm getting this issue too implementing pykube into https://github.com/projectatomic/atomicapp thus I have to create a user for kubernetes when none are provided, ex. `kubectl config set-credentials default --token=foobar`

If no users are provided pykube should still work :)

**Comment by brosner** [comment]
Closing issue as the PR has been merged.
