### ISSUE TITLE
Cannot connect?

### ISSUE THREAD

**Issue by ScubaDrew** [kelproject/pykube#44]
File "/home/drew/.local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname '52.38.116.180' doesn't match either of 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local', 'kubernetes-master'

Can anyone help me with this error?

Thanks!
Drew

**Comment by jayme-github** [comment]
Plesse See issue29

**Comment by ScubaDrew** [comment]
Thanks @jayme-github -- that helped.
