### ISSUE TITLE
Allow ability to bypass cache

### ISSUE THREAD

**Issue by yuvipanda** [kelproject/pykube#52]
In some cases I'm polling the status of pods (due to terrible historical reasons I can not use WATCH). It would be awesome if pykube supported a parameter that'll force the query to actually happen and not hit the cache.

Thanks for the nice library!

**Comment by brosner** [comment]
Could you provide some more detail in to your usage of the library? There are ways of invalidating the internal cache to ensure it queries when you want it to.
