### ISSUE TITLE
Ability to use pykube from inside a container running in Kubernetes

### ISSUE THREAD

**Issue by pcm32** [kelproject/pykube#54]
If you get a shell in a container that is currently running inside a kubernetes cluster, and install kubectl, you can access the Kubernetes cluster from the inside. There is however no kubeconfig file used, yet still kubectl manages to contact the master node and create API objects. The only thing exposed on the environment I found was:

```bash
root@my-busybox-lc4bi:~# env | grep 'KUBERNETES'
KUBERNETES_PORT=tcp://10.100.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=10.100.0.1
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_ADDR=10.100.0.1
KUBERNETES_PORT_443_TCP=tcp://10.100.0.1:443
```

so I presume that kubectl must be using something like this to contact the master, but I'm not sure. It would be great if pykube could be able to contact the Kubernetes master from inside a container running in the cluster in the same way as kubectl manages to do without a kubeconfig file. We need this functionality for our main use case with the Galaxy workflow environment. I would be happy to contribute to this with some guidance, as I don't see very clearly how to approach this.

**Comment by jayme-github** [comment]
You could use the `from_service_account` method of KubeConfig:
https://github.com/kelproject/pykube/blob/760d2671857f8d564c508fc8491438e111696962/pykube/config.py#L21

**Comment by pcm32** [comment]
thanks @jayme-github! I'm sorry I didn't spot that functionality, should have checked again! This issue is redundant and I will close it.
