### ISSUE TITLE
KeyError: 'client-certificate'

### ISSUE THREAD

**Issue by veerendra2** [kelproject/pykube#55]
Hi,
I followed this [https://pypi.python.org/pypi/pykube/](https://pypi.python.org/pypi/pykube/) to query for all ready pods. I'm getting the KeyError: 'client-certificate' error.
```
>>> import operator
>>> import pykube
>>> api = pykube.HTTPClient(pykube.KubeConfig.from_file("/root/.kube/config"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/pykube/http.py", line 33, in __init__
    self.session = self.build_session()
  File "/usr/local/lib/python3.5/site-packages/pykube/http.py", line 57, in build_session
    self.config.user["client-certificate"].filename(),
KeyError: 'client-certificate'
```
Im using Python 3.5

**Comment by parasit** [comment]
Same error here, in python 2.7

**Comment by tobegit3hub** [comment]
Same issue with python 2.7.6 when `pip install pykube`.

Thanks for @parasit  and it works after `python setup.py install` with the latest source code.

I think this's resolved and you're welcome to close it 😃

**Comment by paultiplady** [comment]
I think this is due to a change in the kube config schema, probably due to the 1.3.x kubectl client.

a006ed80327a8add6ba7c8d4c88f3c479b87a4f1 seems to put in a fix for the error.

Given that the current release is broken against kubectl v1.3 without this fix, can we get a new pypi release please?

**Comment by Chris-Dee** [comment]
When can we expect the next pypi release so that `pip install pykube` doesn't give this issue since its fixed in the source code?

**Comment by brosner** [comment]
Very soon. I need to review a couple more things before the release, but haven't had the time yet. I'll make that time today or tomorrow.

**Comment by brosner** [comment]
v0.13.0 has been tagged and released.
