### ISSUE TITLE
ssl and token issue with from_service_account

### ISSUE THREAD

**Issue by spdeshpande** [kelproject/pykube#57]
Hi,

Found two issues with pykube.KubeConfig.from_service_account.

1) Cannot turn SSL verification off. 

There has to be a way to either specify the verify flag when calling the pykube api or set the verify to False in HttpClient.build_session() when no "certificate-authority" is found in self.config.cluster

2) The token read in KubeConfig.from_service_account appends a newline at the end of the token making it an invalid header value. 

This can be fixed with: token = fp.read().rstrip('\n')

Thanks,
Sudeep

**Comment by stevezau** [comment]
how did u end up disabling the ssl verify?
