### ISSUE TITLE
Support PetSet

### ISSUE THREAD

**Issue by tobegit3hub** [kelproject/pykube#61]
Now we are using `PetSet` to deploy our cluster applications. We accept request in `Django` and it would be better to access `Kubernetes` with Python SDK like `pykube`.

After reading https://github.com/kelproject/pykube/blob/99e193a81f59044e1d6f3a3b96e6e33853059749/pykube/__init__.py , I thinks `pykube` doesn't support `PetSet` yet. Is it possible to support `PetSet`? 

We're also glad to test it.

**Comment by brosner** [comment]
We don't have a `PetSet` class yet, but adding one is super simple! I might try to get to it this weekend and if not I will next week, but if a PR comes in sooner even better :-)

**Comment by tobegit3hub** [comment]
Looks great. Thanks for supporting 👍
