### ISSUE TITLE
Using pykube inside the cluster

### ISSUE THREAD

**Issue by diegodelemos** [kelproject/pykube#82]
Hello,

Is `pykube` prepared to be executed inside a pod and make calls to the Kubernetes API? I need to query it to know the state of a Job, and if it has not ended (no successful nor fail) I would like to wait until it happens.

Thanks so much!

**Comment by diegodelemos** [comment]
I suppose it is possible since [here](https://github.com/kelproject/pykube/blob/master/pykube/config.py#L21-L60) the `config.py` is prepared to retrieve the credentials from a pod.

**Comment by brosner** [comment]
To give an official answer, yes, pykube is very capable of making calls within the cluster. The classmethod you link to is exactly the way to do it too.

I can vouch for pykube running in-cluster in production and it works great!

**Comment by mdavis-xyz** [comment]
How do you use it within the cluster? I get an error because the `api` object does not have a `config` attributes.

MWE:

```
import pykube                  
api = pykube.KubeConfig.from_service_account()             
pykube.Service.objects(api)
```

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pykube/objects.py", line 17, in __call__
    namespace = api.config.namespace
AttributeError: 'KubeConfig' object has no attribute 'config'
```
